import asyncio
from pyrogram import Client

API_ID = 2184829
API_HASH = "6930b92388baabff4cb4a1d377085035"

app = Client("AlinaSession", API_ID, API_HASH, in_memory=True)

async def main():
    await app.start()
    ss = await app.export_session_string()
    xx = f"HERE IS YOUR STRING SESSION, COPY IT, DON'T SHARE!!\n\n`{ss}`\n\nGENERATED BY @AlinaMusic_Support"
    await app.send_message("me", xx)
    print("\nHERE IS YOUR STRING SESSION, COPY IT, DON'T SHARE!!\n")
    print(f"\n{ss}\n") 
    print("\nGENERATED BY ALINA MUSIC BOT\n")


asyncio.run(main())
